# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Metric(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, base: bool=None):  # noqa: E501
        """Metric - a model defined in Swagger

        :param name: The name of this Metric.  # noqa: E501
        :type name: str
        :param base: The base of this Metric.  # noqa: E501
        :type base: bool
        """
        self.swagger_types = {
            'name': str,
            'base': bool
        }

        self.attribute_map = {
            'name': 'name',
            'base': 'base'
        }

        self._name = name
        self._base = base

    @classmethod
    def from_dict(cls, dikt) -> 'Metric':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Metric of this Metric.  # noqa: E501
        :rtype: Metric
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this Metric.


        :return: The name of this Metric.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Metric.


        :param name: The name of this Metric.
        :type name: str
        """

        self._name = name

    @property
    def base(self) -> bool:
        """Gets the base of this Metric.


        :return: The base of this Metric.
        :rtype: bool
        """
        return self._base

    @base.setter
    def base(self, base: bool):
        """Sets the base of this Metric.


        :param base: The base of this Metric.
        :type base: bool
        """

        self._base = base
