# coding: utf-8

from __future__ import absolute_import

from rest_api.swagger_server.models.base_model_ import Model
from rest_api.swagger_server import util


class Metadata(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, name: str=None, value: str=None):  # noqa: E501
        """Metadata - a model defined in Swagger

        :param id: The id of this Metadata.  # noqa: E501
        :type id: str
        :param name: The name of this Metadata.  # noqa: E501
        :type name: str
        :param value: The value of this Metadata.  # noqa: E501
        :type value: str
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'value': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'value': 'value'
        }

        self._id = id
        self._name = name
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'Metadata':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Metadata of this Metadata.  # noqa: E501
        :rtype: Metadata
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Metadata.

        Unique identifier / alias / slug  # noqa: E501

        :return: The id of this Metadata.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Metadata.

        Unique identifier / alias / slug  # noqa: E501

        :param id: The id of this Metadata.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Metadata.

        Detailed information about this metadata e.g. what kind of values we should expect  # noqa: E501

        :return: The name of this Metadata.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Metadata.

        Detailed information about this metadata e.g. what kind of values we should expect  # noqa: E501

        :param name: The name of this Metadata.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def value(self) -> str:
        """Gets the value of this Metadata.

        Value, format or type depends of type but should be string in general. It has `null` value when metadata value is not specified.  # noqa: E501

        :return: The value of this Metadata.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value: str):
        """Sets the value of this Metadata.

        Value, format or type depends of type but should be string in general. It has `null` value when metadata value is not specified.  # noqa: E501

        :param value: The value of this Metadata.
        :type value: str
        """

        self._value = value
