# coding: utf-8

from __future__ import absolute_import

from typing import List, Dict  # noqa: F401

from rest_api.swagger_server.models.base_model_ import Model
from rest_api.swagger_server import util


class Metric(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, description: str=None, parent_id: str=None, unit: str=None, moving_window_duration: int=None, interval: int=None, removable: bool=None, hosts: List[str]=None):  # noqa: E501
        """Metric - a model defined in Swagger

        :param id: The id of this Metric.  # noqa: E501
        :type id: str
        :param description: The description of this Metric.  # noqa: E501
        :type description: str
        :param parent_id: The parent_id of this Metric.  # noqa: E501
        :type parent_id: str
        :param unit: The unit of this Metric.  # noqa: E501
        :type unit: str
        :param moving_window_duration: The moving_window_duration of this Metric.  # noqa: E501
        :type moving_window_duration: int
        :param interval: The interval of this Metric.  # noqa: E501
        :type interval: int
        :param removable: The removable of this Metric.  # noqa: E501
        :type removable: bool
        :param hosts: The hosts of this Metric.  # noqa: E501
        :type hosts: List[str]
        """
        self.swagger_types = {
            'id': str,
            'description': str,
            'parent_id': str,
            'unit': str,
            'moving_window_duration': int,
            'interval': int,
            'removable': bool,
            'hosts': List[str]
        }

        self.attribute_map = {
            'id': 'id',
            'description': 'description',
            'parent_id': 'parent_id',
            'unit': 'unit',
            'moving_window_duration': 'moving_window_duration',
            'interval': 'interval',
            'removable': 'removable',
            'hosts': 'hosts'
        }

        self._id = id
        self._description = description
        self._parent_id = parent_id
        self._unit = unit
        self._moving_window_duration = moving_window_duration
        self._interval = interval
        self._removable = removable
        self._hosts = hosts

    @classmethod
    def from_dict(cls, dikt) -> 'Metric':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Metric of this Metric.  # noqa: E501
        :rtype: Metric
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Metric.

        Metric slug name. For basic metrics this is e.g. `ram`, `cpu`. For complex metrics this is concatenation produced as `cpx_{parent_id}_{moving_window_duration}_{interval}`  # noqa: E501

        :return: The id of this Metric.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Metric.

        Metric slug name. For basic metrics this is e.g. `ram`, `cpu`. For complex metrics this is concatenation produced as `cpx_{parent_id}_{moving_window_duration}_{interval}`  # noqa: E501

        :param id: The id of this Metric.
        :type id: str
        """

        self._id = id

    @property
    def description(self) -> str:
        """Gets the description of this Metric.

        Detailed informations about metric  # noqa: E501

        :return: The description of this Metric.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Metric.

        Detailed informations about metric  # noqa: E501

        :param description: The description of this Metric.
        :type description: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def parent_id(self) -> str:
        """Gets the parent_id of this Metric.

        Id of a metric on which is based the complex metric. For basic metric this value is set as `null`.  # noqa: E501

        :return: The parent_id of this Metric.
        :rtype: str
        """
        return self._parent_id

    @parent_id.setter
    def parent_id(self, parent_id: str):
        """Sets the parent_id of this Metric.

        Id of a metric on which is based the complex metric. For basic metric this value is set as `null`.  # noqa: E501

        :param parent_id: The parent_id of this Metric.
        :type parent_id: str
        """

        self._parent_id = parent_id

    @property
    def unit(self) -> str:
        """Gets the unit of this Metric.

        String that should be appended to chart tooltip / legend eq. `%` or `Mb`  # noqa: E501

        :return: The unit of this Metric.
        :rtype: str
        """
        return self._unit

    @unit.setter
    def unit(self, unit: str):
        """Sets the unit of this Metric.

        String that should be appended to chart tooltip / legend eq. `%` or `Mb`  # noqa: E501

        :param unit: The unit of this Metric.
        :type unit: str
        """
        if unit is None:
            raise ValueError("Invalid value for `unit`, must not be `None`")  # noqa: E501

        self._unit = unit

    @property
    def moving_window_duration(self) -> int:
        """Gets the moving_window_duration of this Metric.

        Duration of moving window in seconds  # noqa: E501

        :return: The moving_window_duration of this Metric.
        :rtype: int
        """
        return self._moving_window_duration

    @moving_window_duration.setter
    def moving_window_duration(self, moving_window_duration: int):
        """Sets the moving_window_duration of this Metric.

        Duration of moving window in seconds  # noqa: E501

        :param moving_window_duration: The moving_window_duration of this Metric.
        :type moving_window_duration: int
        """

        self._moving_window_duration = moving_window_duration

    @property
    def interval(self) -> int:
        """Gets the interval of this Metric.

        Number of seconds between each new point in produced series  # noqa: E501

        :return: The interval of this Metric.
        :rtype: int
        """
        return self._interval

    @interval.setter
    def interval(self, interval: int):
        """Sets the interval of this Metric.

        Number of seconds between each new point in produced series  # noqa: E501

        :param interval: The interval of this Metric.
        :type interval: int
        """

        self._interval = interval

    @property
    def removable(self) -> bool:
        """Gets the removable of this Metric.

        True if metric is owned by logged user  # noqa: E501

        :return: The removable of this Metric.
        :rtype: bool
        """
        return self._removable

    @removable.setter
    def removable(self, removable: bool):
        """Sets the removable of this Metric.

        True if metric is owned by logged user  # noqa: E501

        :param removable: The removable of this Metric.
        :type removable: bool
        """

        self._removable = removable

    @property
    def hosts(self) -> List[str]:
        """Gets the hosts of this Metric.

        Array of hostnames  # noqa: E501

        :return: The hosts of this Metric.
        :rtype: List[str]
        """
        return self._hosts

    @hosts.setter
    def hosts(self, hosts: List[str]):
        """Sets the hosts of this Metric.

        Array of hostnames  # noqa: E501

        :param hosts: The hosts of this Metric.
        :type hosts: List[str]
        """

        self._hosts = hosts
